name:                sync
version:             0.1.0.0
github:              "tim-band/sync"
license:             BSD3
author:              "Tim Band"
maintainer:          "example@example.com"
copyright:           "2020 Tim Band"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/tim-band/sync#readme>

dependencies:
- base >= 4.7 && < 5
- filepath >= 1.4.2.1 && < 2
- yaml >= 0.11.4.0 && < 0.12
- aeson >= 1.4.7.1 && < 2
- mountpoints >= 1.0.2 && < 2
- unix >= 2.7.2.0 && < 3
- directory >= 1.3.6.0 && < 2
- vector >= 0.12.1.2 && < 0.13
- extra >= 1.6.21 && < 2
- text >= 1.2.4.0 && < 2
- time >= 1.9.2 && < 2
- cmdargs >= 0.10.20 && < 0.11
- process >= 1.6.8.0 && < 2
- transformers >= 0.5.6.2 && < 0.6
- containers >= 0.6.2.1 && < 0.7
- unordered-containers >= 0.2.1.0 && < 0.3
- hsexif >= 0.6.1.8 && < 0.7

library:
  source-dirs: src

executables:
  sync-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - sync

tests:
  sync-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - sync
